/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import javax.swing.JInternalFrame;

/**
 *
 * @author Lenovo
 */
public class FrmAdministrador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAdministrador.class.getName());

    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dppFondo = new javax.swing.JDesktopPane();
        lblBienvenida = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuRegistro = new javax.swing.JMenu();
        mniUsuarios = new javax.swing.JMenuItem();
        mniMedicos = new javax.swing.JMenuItem();
        mniHorarios = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mniRoles = new javax.swing.JMenuItem();
        mniBloquearUsuario = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mniReporte = new javax.swing.JMenuItem();
        mniExcel = new javax.swing.JMenuItem();
        mnuAgendaMedica = new javax.swing.JMenu();
        mniAgenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Bienvenido!");

        lblPregunta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPregunta.setText("Que va a hacer hoy?");

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");

        dppFondo.setLayer(lblBienvenida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dppFondo.setLayer(lblPregunta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dppFondo.setLayer(btnCerrarSesion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dppFondoLayout = new javax.swing.GroupLayout(dppFondo);
        dppFondo.setLayout(dppFondoLayout);
        dppFondoLayout.setHorizontalGroup(
            dppFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dppFondoLayout.createSequentialGroup()
                .addGroup(dppFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dppFondoLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(lblPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dppFondoLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnCerrarSesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dppFondoLayout.createSequentialGroup()
                .addGap(0, 172, Short.MAX_VALUE)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        dppFondoLayout.setVerticalGroup(
            dppFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dppFondoLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        mnuRegistro.setText("Registro");

        mniUsuarios.setText("Registrar Usuarios");
        mniUsuarios.addActionListener(this::mniUsuariosActionPerformed);
        mnuRegistro.add(mniUsuarios);

        mniMedicos.setText("Registrar Medicos");
        mnuRegistro.add(mniMedicos);

        mniHorarios.setText("Registrar Horarios");
        mniHorarios.addActionListener(this::mniHorariosActionPerformed);
        mnuRegistro.add(mniHorarios);

        jMenuBar1.add(mnuRegistro);

        mnuUsuarios.setText("Usuario");

        mniRoles.setText("Administrar Roles");
        mnuUsuarios.add(mniRoles);

        mniBloquearUsuario.setText("Bloquear Usuario");
        mnuUsuarios.add(mniBloquearUsuario);

        jMenuBar1.add(mnuUsuarios);

        mnuReportes.setText("Reportes");

        mniReporte.setText("Generar Reporte");
        mnuReportes.add(mniReporte);

        mniExcel.setText("Exportar a Excel");
        mnuReportes.add(mniExcel);

        jMenuBar1.add(mnuReportes);

        mnuAgendaMedica.setText("Agenda Medica");

        mniAgenda.setText("Consultar Agenda Medica");
        mnuAgendaMedica.add(mniAgenda);

        jMenuBar1.add(mnuAgendaMedica);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dppFondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dppFondo, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniUsuariosActionPerformed

    private void mniHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHorariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniHorariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAdministrador().setVisible(true));
    }
        private void centrarInternalFrame(JInternalFrame interna) {
        int x = dppFondo.getWidth() / 2 - interna.getWidth() / 2;
        int y = dppFondo.getHeight() / 2 - interna.getHeight() / 2;
        if (interna.isShowing()) {
            interna.setLocation(x, y);
        } else {
            dppFondo.add(interna);
            interna.setLocation(x, y);
            interna.show();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JDesktopPane dppFondo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JMenuItem mniAgenda;
    private javax.swing.JMenuItem mniBloquearUsuario;
    private javax.swing.JMenuItem mniExcel;
    private javax.swing.JMenuItem mniHorarios;
    private javax.swing.JMenuItem mniMedicos;
    private javax.swing.JMenuItem mniReporte;
    private javax.swing.JMenuItem mniRoles;
    private javax.swing.JMenuItem mniUsuarios;
    private javax.swing.JMenu mnuAgendaMedica;
    private javax.swing.JMenu mnuRegistro;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
