/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import javax.swing.JInternalFrame;

/**
 *
 * @author Lenovo
 */
public class FrmRecepcionista extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRecepcionista.class.getName());

    /**
     * Creates new form FrmAdministrador
     */
    public FrmRecepcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dppFondo = new javax.swing.JDesktopPane();
        lblBienvenida = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPaciente = new javax.swing.JMenu();
        mniPaciente = new javax.swing.JMenuItem();
        mniModificar = new javax.swing.JMenuItem();
        mniConsulta = new javax.swing.JMenuItem();
        mniBuscar = new javax.swing.JMenuItem();
        mnuCitas = new javax.swing.JMenu();
        mniRegistrarCita = new javax.swing.JMenuItem();
        mniReprogramar = new javax.swing.JMenuItem();
        mniCancelar = new javax.swing.JMenuItem();
        mnuOtro = new javax.swing.JMenu();
        mniRegistrarInfo = new javax.swing.JMenuItem();
        mniConsultaMedicos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Bienvenido!");

        lblPregunta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPregunta.setText("Que va a hacer hoy?");

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");

        dppFondo.setLayer(lblBienvenida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dppFondo.setLayer(lblPregunta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dppFondo.setLayer(btnCerrarSesion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dppFondoLayout = new javax.swing.GroupLayout(dppFondo);
        dppFondo.setLayout(dppFondoLayout);
        dppFondoLayout.setHorizontalGroup(
            dppFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dppFondoLayout.createSequentialGroup()
                .addGroup(dppFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dppFondoLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(lblPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dppFondoLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnCerrarSesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dppFondoLayout.createSequentialGroup()
                .addGap(0, 172, Short.MAX_VALUE)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        dppFondoLayout.setVerticalGroup(
            dppFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dppFondoLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        mnuPaciente.setText("Paciente");

        mniPaciente.setText("Registrar Paciente");
        mniPaciente.addActionListener(this::mniPacienteActionPerformed);
        mnuPaciente.add(mniPaciente);

        mniModificar.setText("Modificar Paciente");
        mnuPaciente.add(mniModificar);

        mniConsulta.setText("Consultar Paciente");
        mniConsulta.addActionListener(this::mniConsultaActionPerformed);
        mnuPaciente.add(mniConsulta);

        mniBuscar.setText("Buscar Paciente");
        mnuPaciente.add(mniBuscar);

        jMenuBar1.add(mnuPaciente);

        mnuCitas.setText("Cita");

        mniRegistrarCita.setText("Registrar Cita Medica");
        mnuCitas.add(mniRegistrarCita);

        mniReprogramar.setText("Reprogramar Cita");
        mnuCitas.add(mniReprogramar);

        mniCancelar.setText("Cancelar Cita");
        mnuCitas.add(mniCancelar);

        jMenuBar1.add(mnuCitas);

        mnuOtro.setText("Otro");

        mniRegistrarInfo.setText("Registrar Info del Seguro Medico");
        mnuOtro.add(mniRegistrarInfo);

        mniConsultaMedicos.setText("Consultar Disponibilidad de Medicos");
        mnuOtro.add(mniConsultaMedicos);

        jMenuBar1.add(mnuOtro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dppFondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dppFondo, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniPacienteActionPerformed

    private void mniConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRecepcionista().setVisible(true));
    }

    private void centrarInternalFrame(JInternalFrame interna) {
        int x = dppFondo.getWidth() / 2 - interna.getWidth() / 2;
        int y = dppFondo.getHeight() / 2 - interna.getHeight() / 2;
        if (interna.isShowing()) {
            interna.setLocation(x, y);
        } else {
            dppFondo.add(interna);
            interna.setLocation(x, y);
            interna.show();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JDesktopPane dppFondo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JMenuItem mniBuscar;
    private javax.swing.JMenuItem mniCancelar;
    private javax.swing.JMenuItem mniConsulta;
    private javax.swing.JMenuItem mniConsultaMedicos;
    private javax.swing.JMenuItem mniModificar;
    private javax.swing.JMenuItem mniPaciente;
    private javax.swing.JMenuItem mniRegistrarCita;
    private javax.swing.JMenuItem mniRegistrarInfo;
    private javax.swing.JMenuItem mniReprogramar;
    private javax.swing.JMenu mnuCitas;
    private javax.swing.JMenu mnuOtro;
    private javax.swing.JMenu mnuPaciente;
    // End of variables declaration//GEN-END:variables
}
