/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author IVAN GUEVARA
 */
public class IfrmReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmReportes
     */
    public IfrmReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReportesDePacientesPorEspecialidad = new javax.swing.JLabel();
        btnExportarExcel = new javax.swing.JButton();
        btnExportarPDF = new javax.swing.JButton();

        lblReportesDePacientesPorEspecialidad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblReportesDePacientesPorEspecialidad.setText("\"Reporte de Pacientes por Especialidad");

        btnExportarExcel.setText("Exportar a Excel");
        btnExportarExcel.setActionCommand("Exportar a Excel");
        btnExportarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarExcelActionPerformed(evt);
            }
        });

        btnExportarPDF.setText("Exportar a PDF");
        btnExportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExportarExcel)
                .addGap(156, 156, 156)
                .addComponent(btnExportarPDF)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblReportesDePacientesPorEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblReportesDePacientesPorEspecialidad)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarPDF)
                    .addComponent(btnExportarExcel))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarExcelActionPerformed
       javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Guardar Reporte Excel");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos Excel (*.xlsx)", "xlsx"));
        
        int seleccion = fileChooser.showSaveDialog(this);
        
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivoGuardar = fileChooser.getSelectedFile();
            String ruta = archivoGuardar.getAbsolutePath();
            
           
            if (!ruta.toLowerCase().endsWith(".xlsx")) {
                ruta += ".xlsx";
            }
            
            try {
              
                utilidades.IExportadorReporte exportadorExcel = new utilidades.AdaptadorExcel();
                
               
                boolean exito = logica.BLReportes.exportarReporteEspecialidades(exportadorExcel, ruta);
                
                if (exito) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Reporte Excel generado correctamente en:\n" + ruta, "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (excepciones.DatosInvalidosException ex) {
                
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al exportar: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExportarExcelActionPerformed

    private void btnExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPDFActionPerformed
       javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Guardar Reporte PDF");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos PDF (*.pdf)", "pdf"));
        
        int seleccion = fileChooser.showSaveDialog(this);
        
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivoGuardar = fileChooser.getSelectedFile();
            String ruta = archivoGuardar.getAbsolutePath();
            
            if (!ruta.toLowerCase().endsWith(".pdf")) {
                ruta += ".pdf";
            }
            
            try {
                utilidades.IExportadorReporte exportadorPDF = new utilidades.AdaptadorPDF();
                
                boolean exito = logica.BLReportes.exportarReporteEspecialidades(exportadorPDF, ruta);
                
                if (exito) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Reporte PDF generado correctamente en:\n" + ruta, "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (excepciones.DatosInvalidosException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al exportar: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExportarPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarExcel;
    private javax.swing.JButton btnExportarPDF;
    private javax.swing.JLabel lblReportesDePacientesPorEspecialidad;
    // End of variables declaration//GEN-END:variables
}
