/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import entidades.*;
import java.time.*;
import java.util.*;
import javax.swing.JOptionPane;
import logica.*;

/**
 *
 * @author Lenovo
 */
public class IfrmReprogramarCita extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmReprogramarCita
     */
    public IfrmReprogramarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHoraInicio = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();
        btnReprogramar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblRegistrarCita = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        dtcFecha = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();

        lblHoraInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHoraInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoraInicio.setText("<html>Hora de Inicio: (HH:mm)</html>");

        txtHoraInicio.setEnabled(false);

        btnReprogramar.setText("Reprogramar");
        btnReprogramar.setEnabled(false);
        btnReprogramar.addActionListener(this::btnReprogramarActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        lblRegistrarCita.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRegistrarCita.setText("Reprogramar Cita");

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblId.setText("ID de la Cita:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFecha.setText("Fecha de la Cita:");

        dtcFecha.setEnabled(false);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblRegistrarCita))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFecha)
                                    .addComponent(lblId)
                                    .addComponent(lblHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReprogramar)
                        .addGap(45, 45, 45)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblRegistrarCita)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(dtcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReprogramar)
                    .addComponent(btnSalir)
                    .addComponent(btnBuscar))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReprogramarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReprogramarActionPerformed
        String idCita = txtId.getText();
        try {
            Date fechaDate = dtcFecha.getDate();
            LocalDate fecha = fechaDate.toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();
            LocalTime horaInicio = LocalTime.parse(txtHoraInicio.getText());
            boolean exito = BLCita.reprogramarCita(Integer.valueOf(idCita), fecha, horaInicio);
            if (exito) {
                JOptionPane.showMessageDialog(this,
                        "Cita registrada exitosamente.",
                        "Éxito", 1);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo completar el registro.",
                        "Error", 0);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Por favor verifique que todos los campos esten correctos.",
                    "Error", 0);
        }
    }//GEN-LAST:event_btnReprogramarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        try {
            activar();
            txtId.setEnabled(false);
            int id = Integer.parseInt(txtId.getText().trim());
            Cita cita = BLCita.obtenerDatosCita(id);
            LocalDate fecha = cita.getFecha();
            java.util.Date fechaDate = java.sql.Date.valueOf(fecha);
            dtcFecha.setDate(fechaDate);
            txtHoraInicio.setText(cita.getHoraInicio().toString());
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Por favor, Ingrese un DNI valido",
                    JOptionPane.WARNING_MESSAGE);
            limpiar();
            desactivar();
            txtId.setEnabled(true);
            btnReprogramar.setEnabled(false);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private void activar() {
        dtcFecha.setEnabled(true);
        txtHoraInicio.setEnabled(true);
    }
    
    private void desactivar() {
        dtcFecha.setEnabled(false);
        txtHoraInicio.setEnabled(false);
    }
    
    private void limpiar() {
        txtHoraInicio.setText("");
        dtcFecha.setDate(null);
        txtId.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnReprogramar;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JDateChooser dtcFecha;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblRegistrarCita;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
