/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import entidades.*;
import java.util.List;
import javax.swing.JOptionPane;
import logica.BLPaciente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class IfrmBuscarPacientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmBuscarPacientes
     */
    public IfrmBuscarPacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscar = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        txtParametro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarPaciente = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblBuscar.setText("Buscar Paciente");

        lblTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTexto.setText("<html>Escriba su nombre, DNI o historial medico del paciente:</html>");
        lblTexto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblTexto.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tblListarPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Fecha Nacimiento", "Sexo", "Telefono", "Apoderado", "Historial Clinico"
            }
        ));
        tblListarPaciente.setAutoscrolls(false);
        tblListarPaciente.setEnabled(false);
        tblListarPaciente.setRowSelectionAllowed(false);
        tblListarPaciente.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tblListarPaciente);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBuscar)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnSalir))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DefaultTableModel tabla = (DefaultTableModel) tblListarPaciente.getModel();
        tabla.setRowCount(0);
        String sexo, apoderado, parametro = txtParametro.getText();
        try {
            List<Paciente> lista = BLPaciente.buscarPacientes(parametro);
            if (lista != null) {
                
                for (Paciente pac : lista) {
                    if (pac.getSexo() == 'H') {
                        sexo = "Hombre";
                    } else {
                        sexo = "Mujer";
                    }
                    if (pac.getApoderado() == null || pac.getApoderado().trim().isEmpty()) {
                        apoderado = "Sin apoderado";
                    }
                    else {
                        apoderado = pac.getApoderado().trim();
                    }
                    
                    String anio = String.valueOf(pac.getFechaNacimiento().getYear());
                    String mes = String.valueOf(pac.getFechaNacimiento().getMonth().getValue());
                    String dia = String.valueOf(pac.getFechaNacimiento().getDayOfMonth());
                    tabla.addRow(new Object[]{
                        pac.getDni(),
                        pac.getNombres(),
                        (anio + "-" + mes + "-" + dia),
                        sexo,
                        pac.getTelefono(),
                        apoderado,
                        pac.getNumeroHistoriaClinica()}
                    );
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se han registrado pacientes aun", "Error", 0);
            }
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JTable tblListarPaciente;
    private javax.swing.JTextField txtParametro;
    // End of variables declaration//GEN-END:variables
}
