/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import logica.BLFarmacia;
import entidades.Medicamento;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author LENOVO
 */
public class IfrmConsultaStock extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmConsultaStock
     */
    public IfrmConsultaStock() {
        initComponents();
        iniciarReloj();        // Tu reloj
        cargarTablaStock("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDni = new javax.swing.JPanel();
        lblDni = new javax.swing.JLabel();
        txtDniPaciente = new javax.swing.JTextField();
        btnBuscarDni = new javax.swing.JButton();
        lblTexto = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        panIDMedicamento = new javax.swing.JPanel();
        lblMedicamento = new javax.swing.JLabel();
        txtIDMedicamento = new javax.swing.JTextField();
        btnBuscarMedicamento = new javax.swing.JButton();
        btnTodo = new javax.swing.JButton();
        panDetalleMedicamentos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleMedicamento = new javax.swing.JTable();
        panSalir = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();

        panDni.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblDni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDni.setText("DNI O N° DE ATENCION DEL PACIENTE: ");

        txtDniPaciente.addActionListener(this::txtDniPacienteActionPerformed);

        btnBuscarDni.setText("Buscar");
        btnBuscarDni.addActionListener(this::btnBuscarDniActionPerformed);

        javax.swing.GroupLayout panDniLayout = new javax.swing.GroupLayout(panDni);
        panDni.setLayout(panDniLayout);
        panDniLayout.setHorizontalGroup(
            panDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDniPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBuscarDni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDniLayout.setVerticalGroup(
            panDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDniLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txtDniPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDni))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lblTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTexto.setText("FARMACEUTICO- TRUJILLO");

        lblFechaHora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        panIDMedicamento.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblMedicamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMedicamento.setText("ID DEL MEDICAMENTO:");

        txtIDMedicamento.addActionListener(this::txtIDMedicamentoActionPerformed);

        btnBuscarMedicamento.setText("Buscar");
        btnBuscarMedicamento.addActionListener(this::btnBuscarMedicamentoActionPerformed);

        btnTodo.setText("Mostrar Todo");
        btnTodo.addActionListener(this::btnTodoActionPerformed);

        javax.swing.GroupLayout panIDMedicamentoLayout = new javax.swing.GroupLayout(panIDMedicamento);
        panIDMedicamento.setLayout(panIDMedicamentoLayout);
        panIDMedicamentoLayout.setHorizontalGroup(
            panIDMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIDMedicamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMedicamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarMedicamento)
                .addGap(18, 18, 18)
                .addComponent(btnTodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panIDMedicamentoLayout.setVerticalGroup(
            panIDMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIDMedicamentoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panIDMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicamento)
                    .addComponent(txtIDMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMedicamento)
                    .addComponent(btnTodo))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panDetalleMedicamentos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblDetalleMedicamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID med", "Nombre", "Stock Actual", "Stock Minimo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblDetalleMedicamento);

        javax.swing.GroupLayout panDetalleMedicamentosLayout = new javax.swing.GroupLayout(panDetalleMedicamentos);
        panDetalleMedicamentos.setLayout(panDetalleMedicamentosLayout);
        panDetalleMedicamentosLayout.setHorizontalGroup(
            panDetalleMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDetalleMedicamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDetalleMedicamentosLayout.setVerticalGroup(
            panDetalleMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDetalleMedicamentosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panSalir.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout panSalirLayout = new javax.swing.GroupLayout(panSalir);
        panSalir.setLayout(panSalirLayout);
        panSalirLayout.setHorizontalGroup(
            panSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSalirLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panSalirLayout.setVerticalGroup(
            panSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSalirLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFechaHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31)
                        .addComponent(lblTexto))
                    .addComponent(panIDMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panDetalleMedicamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto)
                    .addComponent(lblFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panIDMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDetalleMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniPacienteActionPerformed

    private void btnBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarDniActionPerformed

    private void txtIDMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMedicamentoActionPerformed

    private void btnBuscarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMedicamentoActionPerformed
        cargarTablaStock(txtIDMedicamento.getText());
    }//GEN-LAST:event_btnBuscarMedicamentoActionPerformed

    private void btnTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodoActionPerformed
        txtIDMedicamento.setText("");
        cargarTablaStock("");
    }//GEN-LAST:event_btnTodoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cargarTablaStock(String filtro) {
        DefaultTableModel model = (DefaultTableModel) tblDetalleMedicamento.getModel();
        model.setRowCount(0); // Limpiamos la tabla antes de cargar

        try {
            // Traemos toda la lista original cargada de la base de datos
            List<Medicamento> lista = BLFarmacia.listarInventario("");

            String busqueda = (filtro == null) ? "" : filtro.trim().toLowerCase();
            int coincidencias = 0;

            for (Medicamento m : lista) {
                String idStr = String.valueOf(m.getIdMedicamento()).trim();
                String nombreStr = (m.getNombre() == null) ? "" : m.getNombre().toLowerCase().trim();

                // Evalúa si el texto buscado está en el ID o en el Nombre
                if (busqueda.isEmpty() || idStr.equals(busqueda) || idStr.contains(busqueda) || nombreStr.contains(busqueda)) {
                    String estado = (m.getStockActual() <= m.getStockMinimo()) ? "¡STOCK BAJO!" : "NORMAL";
                    model.addRow(new Object[]{
                        m.getIdMedicamento(),
                        m.getNombre(),
                        m.getStockActual(),
                        m.getStockMinimo(),
                        estado
                    });
                    coincidencias++;
                }
            }

            // Si escribió algo y no encontró coincidencias
            if (coincidencias == 0 && !busqueda.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "El medicamento con ID o Nombre '" + filtro + "' no se encuentra registrado.",
                        "Medicamento No Encontrado",
                        JOptionPane.WARNING_MESSAGE);

                // Recargamos la lista completa para no dejar la pantalla vacía
                cargarTablaStock("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar inventario: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void iniciarReloj() {
        java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("EEEE, d 'de' MMMM 'de' yyyy | hh:mm:ss a", new java.util.Locale("es", "ES"));
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            java.time.LocalDateTime ahora = java.time.LocalDateTime.now();
            String fechaTexto = ahora.format(formato);
            fechaTexto = fechaTexto.substring(0, 1).toUpperCase() + fechaTexto.substring(1);
            lblFechaHora.setText(fechaTexto);
        });
        timer.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDni;
    private javax.swing.JButton btnBuscarMedicamento;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JPanel panDetalleMedicamentos;
    private javax.swing.JPanel panDni;
    private javax.swing.JPanel panIDMedicamento;
    private javax.swing.JPanel panSalir;
    private javax.swing.JTable tblDetalleMedicamento;
    private javax.swing.JTextField txtDniPaciente;
    private javax.swing.JTextField txtIDMedicamento;
    // End of variables declaration//GEN-END:variables
}
