/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author LENOVO
 */
public class IfrmSolicituExamen extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmSolicituExamen
     */
    public IfrmSolicituExamen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panInfoAtencion = new javax.swing.JPanel();
        lblAtencion = new javax.swing.JLabel();
        txtIdAtencion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblPaciente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panSelecionExamen = new javax.swing.JPanel();
        lblTipoExamen = new javax.swing.JLabel();
        txtTipoExamen = new javax.swing.JTextField();
        BtnAgregar = new javax.swing.JButton();
        panDetalleExamenes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExamenes = new javax.swing.JTable();
        btnQuitar = new javax.swing.JButton();
        btnRegistrarSolicitud = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        panInfoAtencion.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de la atencion medica"));

        lblAtencion.setText("IdAtencion:");

        btnBuscar.setText("Buscar");

        lblPaciente.setText("Paciente:");

        jLabel3.setText("Diagnostico:");

        javax.swing.GroupLayout panInfoAtencionLayout = new javax.swing.GroupLayout(panInfoAtencion);
        panInfoAtencion.setLayout(panInfoAtencionLayout);
        panInfoAtencionLayout.setHorizontalGroup(
            panInfoAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoAtencionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panInfoAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInfoAtencionLayout.createSequentialGroup()
                        .addGroup(panInfoAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panInfoAtencionLayout.createSequentialGroup()
                                .addComponent(lblAtencion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInfoAtencionLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        panInfoAtencionLayout.setVerticalGroup(
            panInfoAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoAtencionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInfoAtencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtencion)
                    .addComponent(txtIdAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panSelecionExamen.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccion de examen"));

        lblTipoExamen.setText("Tipo de examen: ");

        txtTipoExamen.addActionListener(this::txtTipoExamenActionPerformed);

        BtnAgregar.setText("Agregar");

        javax.swing.GroupLayout panSelecionExamenLayout = new javax.swing.GroupLayout(panSelecionExamen);
        panSelecionExamen.setLayout(panSelecionExamenLayout);
        panSelecionExamenLayout.setHorizontalGroup(
            panSelecionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSelecionExamenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoExamen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panSelecionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipoExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panSelecionExamenLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BtnAgregar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panSelecionExamenLayout.setVerticalGroup(
            panSelecionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSelecionExamenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panSelecionExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoExamen)
                    .addComponent(txtTipoExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panDetalleExamenes.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de examenes solicitados"));

        tblExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Tipo de examen", "Estado inicia"
            }
        ));
        jScrollPane1.setViewportView(tblExamenes);

        btnQuitar.setText("Quitar");

        javax.swing.GroupLayout panDetalleExamenesLayout = new javax.swing.GroupLayout(panDetalleExamenes);
        panDetalleExamenes.setLayout(panDetalleExamenesLayout);
        panDetalleExamenesLayout.setHorizontalGroup(
            panDetalleExamenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDetalleExamenesLayout.createSequentialGroup()
                .addGroup(panDetalleExamenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDetalleExamenesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDetalleExamenesLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnQuitar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDetalleExamenesLayout.setVerticalGroup(
            panDetalleExamenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDetalleExamenesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuitar)
                .addGap(129, 129, 129))
        );

        btnRegistrarSolicitud.setText("Registrar Solicitud");

        btnLimpiar.setText("limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panSelecionExamen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panInfoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panDetalleExamenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnRegistrarSolicitud)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(30, 30, 30)
                        .addComponent(btnSalir)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panInfoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panSelecionExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDetalleExamenes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarSolicitud)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoExamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoExamenActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnRegistrarSolicitud;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtencion;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblTipoExamen;
    private javax.swing.JPanel panDetalleExamenes;
    private javax.swing.JPanel panInfoAtencion;
    private javax.swing.JPanel panSelecionExamen;
    private javax.swing.JTable tblExamenes;
    private javax.swing.JTextField txtIdAtencion;
    private javax.swing.JTextField txtTipoExamen;
    // End of variables declaration//GEN-END:variables
}
