/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author IVAN GUEVARA
 */

public class IfrmBuscarUsuarioMedico extends javax.swing.JInternalFrame {
    
    private String dniTemp = "";
    private String nombresTemp = "";
    private String apellidosTemp = "";

    /**
     * Creates new form IfrmRegistrarMedico
     */
    public IfrmBuscarUsuarioMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuarioBusqueda = new javax.swing.JLabel();
        txtUsuarioBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDniEncontrado = new javax.swing.JLabel();
        lblNombresEncontrados = new javax.swing.JLabel();
        lblApellidosEncontrados = new javax.swing.JLabel();
        btnLlenarDatos = new javax.swing.JButton();

        lblUsuarioBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuarioBusqueda.setText("Nombre de Usuario:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        lblDniEncontrado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblNombresEncontrados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblApellidosEncontrados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDniEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombresEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidosEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblDniEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblNombresEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblApellidosEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btnLlenarDatos.setText("Llenar Datos");
        btnLlenarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLlenarDatos)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuarioBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsuarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioBusqueda)
                    .addComponent(txtUsuarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnLlenarDatos)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            String nombreUsuario = txtUsuarioBusqueda.getText().trim();
            String[] datosMedico = logica.BLUsuario.buscarUsuarioMedico(nombreUsuario);

            // Guardamos los datos en la memoria de la ventana
            dniTemp = datosMedico[0];
            nombresTemp = datosMedico[1];
            apellidosTemp = datosMedico[2];

            // Mostramos los datos en los JLabels
            lblDniEncontrado.setText("DNI: " + dniTemp);
            lblNombresEncontrados.setText("Nombres: " + nombresTemp);
            lblApellidosEncontrados.setText("Apellidos: " + apellidosTemp);

            // Desbloqueamos el botón para ir a la siguiente ventana
            btnLlenarDatos.setEnabled(true);

        } catch (excepciones.DatosInvalidosException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso de Búsqueda", javax.swing.JOptionPane.WARNING_MESSAGE);
            // Limpiamos la pantalla si hay error
            lblDniEncontrado.setText("");
            lblNombresEncontrados.setText("");
            lblApellidosEncontrados.setText("");
            btnLlenarDatos.setEnabled(false);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de sistema: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLlenarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarDatosActionPerformed
    IfrmCompletarDatosMedico ifrmDatos = new IfrmCompletarDatosMedico(dniTemp, nombresTemp, apellidosTemp);
        
        // Lo agregamos al DesktopPane (asumiendo que tu DesktopPane es accesible)
        this.getParent().add(ifrmDatos);
        ifrmDatos.setLocation(this.getX(), this.getY()); // Para que aparezca en la misma posición
        ifrmDatos.show();
        
        // Cerramos el buscador porque ya no se necesita
        this.dispose();
    }//GEN-LAST:event_btnLlenarDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLlenarDatos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidosEncontrados;
    private javax.swing.JLabel lblDniEncontrado;
    private javax.swing.JLabel lblNombresEncontrados;
    private javax.swing.JLabel lblUsuarioBusqueda;
    private javax.swing.JTextField txtUsuarioBusqueda;
    // End of variables declaration//GEN-END:variables
}
