/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author IVAN GUEVARA
 */
public class IfrmCompletarDatosMedico extends javax.swing.JInternalFrame {

    private String dni;
    private String nombres;
    private String apellidos;

    /**
     * Creates new form IfrmCompletarDatosMedico
     */
    public IfrmCompletarDatosMedico(String dni, String nombres, String apellidos) {
        initComponents();
        this.dni = dni;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblColegiatura = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblFechaDeNacimiento = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        txtColegiatura = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JFormattedTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();

        lblColegiatura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblColegiatura.setText("Colegiatura: ");
        lblColegiatura.setToolTipText("");

        lblEspecialidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEspecialidad.setText("Especialidad");

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefono.setText("Telefono: ");

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDireccion.setText("Direccion: ");

        lblFechaDeNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaDeNacimiento.setText("F. Nacimiento: ");

        lblSexo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSexo.setText("Sexo: ");

        try {
            txtFechaNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", " " }));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblColegiatura)
                    .addComponent(lblEspecialidad)
                    .addComponent(lblTelefono)
                    .addComponent(lblDireccion)
                    .addComponent(lblFechaDeNacimiento)
                    .addComponent(lblSexo))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addComponent(txtColegiatura)
                        .addComponent(txtTelefono)
                        .addComponent(txtDireccion)
                        .addComponent(txtFechaNacimiento)))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColegiatura)
                    .addComponent(txtColegiatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecialidad)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDeNacimiento)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            String colegiatura = txtColegiatura.getText().trim();
            String especialidad = txtEspecialidad.getText().trim();
            String telefono = txtTelefono.getText().trim();
            String direccion = txtDireccion.getText().trim();
            String fechaCruda = txtFechaNacimiento.getText();
            char sexo = cmbSexo.getSelectedItem().toString().charAt(0);

            // 1. VALIDACIÓN GENERAL DE CAMPOS VACÍOS (Soluciona el problema)
            if (colegiatura.isEmpty() || especialidad.isEmpty() || telefono.isEmpty() || direccion.isEmpty() || fechaCruda.replace("-", "").trim().isEmpty()) {
                throw new excepciones.DatosInvalidosException("Por favor, complete todos los campos del formulario antes de registrar.");
            }

            // 2. Si todo está lleno, procedemos a formatear la fecha
            String fechaStr = fechaCruda.trim();
            java.time.format.DateTimeFormatter formatoVisual = java.time.format.DateTimeFormatter
                    .ofPattern("dd-MM-uuuu")
                    .withResolverStyle(java.time.format.ResolverStyle.STRICT);

            java.time.LocalDate fechaNacimiento = java.time.LocalDate.parse(fechaStr, formatoVisual);

            // 3. Enviamos a la capa lógica (donde se validarán las edades, los 9 dígitos, etc.)
            boolean exito = logica.BLMedico.registrarMedico(this.dni, this.nombres, this.apellidos, fechaNacimiento, sexo, telefono, direccion, colegiatura, especialidad);

            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Médico registrado exitosamente en el sistema!");
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar el médico.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (java.time.format.DateTimeParseException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "La fecha está incompleta o no existe en el calendario (Ej. 24-05-1990).", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (excepciones.DatosInvalidosException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de sistema: " + ex.getMessage(), "Error crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JLabel lblColegiatura;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblFechaDeNacimiento;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtColegiatura;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JFormattedTextField txtFechaNacimiento;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
