/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author IVAN GUEVARA
 */
public class IfrmConsultarAgenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmConsultarAgenda
     */
    public IfrmConsultarAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        llblColegiaturaDelMedico = new javax.swing.JLabel();
        txtColegiatura = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        btnBuscarAgenda = new javax.swing.JButton();

        llblColegiaturaDelMedico.setText("Colegiatura del Médico:");

        lblFecha.setText("Fecha:");

        try {
            txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hora Inicio", "Hora Fin", "Estado", "DNI Paciente", "Nombre Paciente"
            }
        ));
        jScrollPane1.setViewportView(tblAgenda);

        btnBuscarAgenda.setText("Buscar Agenda");
        btnBuscarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAgendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarAgenda)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(llblColegiaturaDelMedico)
                    .addComponent(lblFecha))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColegiatura, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(llblColegiaturaDelMedico)
                    .addComponent(txtColegiatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarAgenda)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAgendaActionPerformed
     try {
            String colegiatura = txtColegiatura.getText().trim();
            String fechaCruda = txtFecha.getText();
            
            // 1. Validación de campos vacíos
            if (colegiatura.isEmpty() || fechaCruda.replace("-", "").trim().isEmpty()) {
                throw new excepciones.DatosInvalidosException("Por favor, ingrese la colegiatura y la fecha para buscar.");
            }
            
            // 2. Dar formato a la fecha
            String fechaStr = fechaCruda.trim();
            java.time.format.DateTimeFormatter formatoVisual = java.time.format.DateTimeFormatter
                    .ofPattern("dd-MM-uuuu")
                    .withResolverStyle(java.time.format.ResolverStyle.STRICT);
            
            java.time.LocalDate fechaConsulta = java.time.LocalDate.parse(fechaStr, formatoVisual);
            
            // 3. Consultar la capa lógica
            java.util.List<entidades.Cita> listaAgenda = logica.BLCita.consultarAgendaPorMedicoYFecha(colegiatura, fechaConsulta);
            
            // 4. Preparar la tabla
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblAgenda.getModel();
            modelo.setRowCount(0); // Esto limpia la tabla antes de mostrar la nueva búsqueda
            
            // 5. Mostrar mensaje si el doctor no tiene pacientes ese día
            if (listaAgenda.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El médico no tiene pacientes registrados para esta fecha.", "Agenda Libre", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return; // Corta la ejecución aquí para no hacer el ciclo for en vano
            }
            
            // 6. Llenar la tabla fila por fila
            for (entidades.Cita cita : listaAgenda) {
                Object[] fila = new Object[5];
                fila[0] = cita.getHoraInicio();
                fila[1] = cita.getHoraFin();
                fila[2] = cita.getEstado().name();
                fila[3] = cita.getPaciente().getDni();
                fila[4] = cita.getPaciente().getNombres() + " " + cita.getPaciente().getApellidos();
                
                modelo.addRow(fila);
            }
            
        } catch (java.time.format.DateTimeParseException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "La fecha no existe en el calendario o el formato es incorrecto (Ej. 24-05-2026).", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (excepciones.DatosInvalidosException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error crítico de sistema: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarAgendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAgenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel llblColegiaturaDelMedico;
    private javax.swing.JTable tblAgenda;
    private javax.swing.JTextField txtColegiatura;
    private javax.swing.JFormattedTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
