/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import entidades.DetalleReceta;
import javax.swing.Timer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

import logica.BLFarmacia;
import entidades.Medicamento;
import excepciones.DatosInvalidosException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class IfrmEntregaMedicamentos extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmEntregaMedicamentos
     */
    public IfrmEntregaMedicamentos() {
        initComponents();
        iniciarReloj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechaHora = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        panDni = new javax.swing.JPanel();
        lblDni = new javax.swing.JLabel();
        txtDniPaciente = new javax.swing.JTextField();
        btnBuscarDni = new javax.swing.JButton();
        panDetalleReceta = new javax.swing.JPanel();
        lblDetalleRecetaEncontrada = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        lblAtencion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalleReceta = new javax.swing.JTable();
        panBotonEntregarMedicamento = new javax.swing.JPanel();
        btnEntregarMedicamentos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        lblFechaHora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTexto.setText("FARMACEUTICO- TRUJILLO");

        panDni.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblDni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDni.setText("DNI O N° DE ATENCION DEL PACIENTE: ");

        txtDniPaciente.addActionListener(this::txtDniPacienteActionPerformed);

        btnBuscarDni.setText("Buscar");
        btnBuscarDni.addActionListener(this::btnBuscarDniActionPerformed);

        javax.swing.GroupLayout panDniLayout = new javax.swing.GroupLayout(panDni);
        panDni.setLayout(panDniLayout);
        panDniLayout.setHorizontalGroup(
            panDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDniPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBuscarDni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDniLayout.setVerticalGroup(
            panDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDniLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panDniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txtDniPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDni))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panDetalleReceta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblDetalleRecetaEncontrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDetalleRecetaEncontrada.setText("Detalles de la Recete encontra");

        lblPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPaciente.setText("PACIENTE: ");

        lblAtencion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAtencion.setText("ATENCION N°: ");

        tblDetalleReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID med", "Medicamento", "Cantidad solicitada", "Stock Disponible", "Indicaciones"
            }
        ));
        jScrollPane1.setViewportView(tblDetalleReceta);

        javax.swing.GroupLayout panDetalleRecetaLayout = new javax.swing.GroupLayout(panDetalleReceta);
        panDetalleReceta.setLayout(panDetalleRecetaLayout);
        panDetalleRecetaLayout.setHorizontalGroup(
            panDetalleRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDetalleRecetaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDetalleRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDetalleRecetaEncontrada)
                    .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panDetalleRecetaLayout.setVerticalGroup(
            panDetalleRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDetalleRecetaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblDetalleRecetaEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAtencion)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panBotonEntregarMedicamento.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnEntregarMedicamentos.setText("CONFIRMAR Y  REGISTRAR ENTREGA");
        btnEntregarMedicamentos.addActionListener(this::btnEntregarMedicamentosActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout panBotonEntregarMedicamentoLayout = new javax.swing.GroupLayout(panBotonEntregarMedicamento);
        panBotonEntregarMedicamento.setLayout(panBotonEntregarMedicamentoLayout);
        panBotonEntregarMedicamentoLayout.setHorizontalGroup(
            panBotonEntregarMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonEntregarMedicamentoLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnEntregarMedicamentos)
                .addGap(76, 76, 76)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panBotonEntregarMedicamentoLayout.setVerticalGroup(
            panBotonEntregarMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonEntregarMedicamentoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panBotonEntregarMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntregarMedicamentos)
                    .addComponent(btnSalir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFechaHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTexto)
                        .addGap(6, 6, 6))
                    .addComponent(panBotonEntregarMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panDetalleReceta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDetalleReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBotonEntregarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntregarMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarMedicamentosActionPerformed
        try {
            int filaSeleccionada = tblDetalleReceta.getSelectedRow();

            if (filaSeleccionada == -1) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione un medicamento de la lista para entregar.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de registrar la entrega de este medicamento?", "Confirmar Entrega", JOptionPane.YES_NO_OPTION);
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            // Obtenemos ID de la Columna 0 y Cantidad Solicitada de la Columna 2
            int idMedicamento = Integer.parseInt(tblDetalleReceta.getValueAt(filaSeleccionada, 0).toString());
            int cantidadEntregar = Integer.parseInt(tblDetalleReceta.getValueAt(filaSeleccionada, 2).toString());

            // Procesar entrega y descuento de stock
            String mensajeResultado = logica.BLFarmacia.entregarMedicamento(idMedicamento, cantidadEntregar);

            JOptionPane.showMessageDialog(this, mensajeResultado, "Resultado de Entrega", JOptionPane.INFORMATION_MESSAGE);

            // Actualizamos los datos en pantalla
            btnBuscarDniActionPerformed(evt);

        } catch (excepciones.DatosInvalidosException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Atención", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al entregar: " + ex.getMessage(), "Error System", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEntregarMedicamentosActionPerformed

    private void txtDniPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniPacienteActionPerformed

    private void btnBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDniActionPerformed
        String dniOAtencion = txtDniPaciente.getText().trim();

        if (dniOAtencion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el DNI o N° de Atención del paciente.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            entidades.Receta receta = logica.BLFarmacia.buscarReceta(dniOAtencion);

            if (receta == null) {
                JOptionPane.showMessageDialog(this, "No se encontró ninguna receta con el DNI o N° de Atención: " + dniOAtencion, "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            entidades.Paciente p = receta.getAtencionMedica().getCita().getPaciente();
            lblPaciente.setText("PACIENTE: " + p.getNombres() + " " + p.getApellidos());
            lblAtencion.setText("ATENCION N°: " + receta.getAtencionMedica().getIdAtencion());

            // Cargar la tabla con los detalles
            DefaultTableModel model = (DefaultTableModel) tblDetalleReceta.getModel();
            model.setRowCount(0);

            for (entidades.DetalleReceta d : receta.getDetalles()) {
                entidades.Medicamento m = d.getMedicamento();
                model.addRow(new Object[]{
                    m.getIdMedicamento(),
                    m.getNombre(),
                    d.getCantidad(),
                    m.getStockActual(),
                    d.getIndicaciones()
                });
            }

        } catch (excepciones.DatosInvalidosException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Atención", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al procesar la búsqueda: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarDniActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void iniciarReloj() {
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("EEEE, d 'de' MMMM 'de' yyyy | hh:mm:ss a", new Locale("es", "ES"));
        Timer timer = new Timer(1000, e -> {
            LocalDateTime ahora = LocalDateTime.now();
            String fechaTexto = ahora.format(formato);
            fechaTexto = fechaTexto.substring(0, 1).toUpperCase() + fechaTexto.substring(1);

            lblFechaHora.setText(fechaTexto);
        });

        timer.start(); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDni;
    private javax.swing.JButton btnEntregarMedicamentos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtencion;
    private javax.swing.JLabel lblDetalleRecetaEncontrada;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JPanel panBotonEntregarMedicamento;
    private javax.swing.JPanel panDetalleReceta;
    private javax.swing.JPanel panDni;
    private javax.swing.JTable tblDetalleReceta;
    private javax.swing.JTextField txtDniPaciente;
    // End of variables declaration//GEN-END:variables
}
