/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import entidades.Cita;
import excepciones.DatosInvalidosException;
import javax.swing.JOptionPane;
import logica.BLAtencionMedica;
import logica.BLCita;

/**
 *
 * @author LENOVO
 */
public class IfrmRegistrarDiagnostico extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmRegistroSignosVitales
     */
    public IfrmRegistrarDiagnostico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panInfoCita = new javax.swing.JPanel();
        lblIdCita = new javax.swing.JLabel();
        txtIdCita = new javax.swing.JTextField();
        btnBuscarCita = new javax.swing.JButton();
        lblNombrePaciente = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        panDiagnostico = new javax.swing.JPanel();
        lblMotivoConsulta = new javax.swing.JLabel();
        lblSignoVitales = new javax.swing.JLabel();
        txtMotivoConsulta = new javax.swing.JTextField();
        txtSignosVitales = new javax.swing.JTextField();
        lblAntecentes = new javax.swing.JLabel();
        txtAntecedentes = new javax.swing.JTextField();
        lblDiagnostico = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        lb = new javax.swing.JLabel();
        TxtObservaciones = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTratamiento = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        panInfoCita.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Cita"));

        lblIdCita.setText("ID CITA: ");

        btnBuscarCita.setText("Buscar Cita");
        btnBuscarCita.addActionListener(this::btnBuscarCitaActionPerformed);

        lblNombrePaciente.setText("Nombre del Paciente:");

        lblEstado.setText("Estado: ");

        javax.swing.GroupLayout panInfoCitaLayout = new javax.swing.GroupLayout(panInfoCita);
        panInfoCita.setLayout(panInfoCitaLayout);
        panInfoCitaLayout.setHorizontalGroup(
            panInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoCitaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInfoCitaLayout.createSequentialGroup()
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panInfoCitaLayout.createSequentialGroup()
                        .addComponent(lblIdCita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdCita, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnBuscarCita)
                        .addGap(35, 35, 35)
                        .addComponent(lblNombrePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panInfoCitaLayout.setVerticalGroup(
            panInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfoCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInfoCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCita)
                    .addComponent(lblNombrePaciente)
                    .addComponent(lblIdCita))
                .addGap(18, 18, 18)
                .addComponent(lblEstado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panDiagnostico.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle del Diganostico"));

        lblMotivoConsulta.setText("Motivo de consulta:");

        lblSignoVitales.setText("Signos Vitales:");

        txtSignosVitales.setEnabled(false);

        lblAntecentes.setText("Antecedentes:");

        lblDiagnostico.setText("Diagnostico:");

        txtDiagnostico.addActionListener(this::txtDiagnosticoActionPerformed);

        lb.setText("Observaciones:");

        jLabel1.setText("Tratamiento:");

        javax.swing.GroupLayout panDiagnosticoLayout = new javax.swing.GroupLayout(panDiagnostico);
        panDiagnostico.setLayout(panDiagnosticoLayout);
        panDiagnosticoLayout.setHorizontalGroup(
            panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDiagnosticoLayout.createSequentialGroup()
                .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDiagnosticoLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel5))
                    .addGroup(panDiagnosticoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb)
                            .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMotivoConsulta)
                                    .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSignoVitales)
                                        .addComponent(lblAntecentes)))
                                .addComponent(lblDiagnostico, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMotivoConsulta)
                            .addComponent(txtSignosVitales)
                            .addComponent(txtAntecedentes)
                            .addComponent(txtDiagnostico)
                            .addComponent(TxtObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addComponent(txtTratamiento))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDiagnosticoLayout.setVerticalGroup(
            panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDiagnosticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotivoConsulta)
                    .addComponent(txtMotivoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSignoVitales)
                    .addComponent(txtSignosVitales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAntecentes)
                    .addComponent(txtAntecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiagnostico))
                .addGap(18, 18, 18)
                .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb)
                    .addComponent(TxtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panInfoCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnGuardar)
                        .addGap(73, 73, 73)
                        .addComponent(btnLimpiar)
                        .addGap(82, 82, 82)
                        .addComponent(btnSalir)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panInfoCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosticoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCitaActionPerformed
        try {
            if (txtIdCita.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID de Cita.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idCita = Integer.parseInt(txtIdCita.getText().trim());

            // 1. Buscamos primero la cita (Valida si existe o está cancelada)
            Cita cita = logica.BLCita.obtenerDatosCitaConPaciente(idCita);

            if (cita != null && cita.getPaciente() != null) {
                String nombreCompleto = cita.getPaciente().getNombres() + " " + cita.getPaciente().getApellidos();
                lblNombrePaciente.setText("Nombre del Paciente: " + nombreCompleto);
                lblEstado.setText("Estado: " + cita.getEstado().name());

                // 2. Buscamos los signos vitales registrados por la enfermera
                String signosVitales = logica.BLAtencionMedica.obtenerSignosVitalesPorCita(idCita);

                if (signosVitales == null || signosVitales.trim().isEmpty()) {
                    txtSignosVitales.setText("");
                    btnGuardar.setEnabled(false);

                    JOptionPane.showMessageDialog(this,
                            "⚠️ La Cita #" + idCita + " fue encontrada, pero AÚN NO se han registrado los signos vitales por la enfermera.",
                            "Triaje Pendiente",
                            JOptionPane.WARNING_MESSAGE);
                } else {
                    txtSignosVitales.setText(signosVitales);
                    btnGuardar.setEnabled(true);
                    JOptionPane.showMessageDialog(this, "Cita seleccionada con éxito.", "Información", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Cita debe ser un número entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (DatosInvalidosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Atención", JOptionPane.WARNING_MESSAGE);
            lblNombrePaciente.setText("Nombre del Paciente: -");
            lblEstado.setText("Estado: -");
            txtSignosVitales.setText("");
            btnGuardar.setEnabled(false);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al buscar cita: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarCitaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (txtIdCita.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe buscar una cita antes de guardar.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idCita = Integer.parseInt(txtIdCita.getText().trim());

            // Al guardar, obtenemos la Cita actual (que vendrá con estado CONFIRMADA de la BD)
            Cita citaReal = logica.BLCita.obtenerDatosCitaConPaciente(idCita);

            // Guardamos la atención médica
            boolean exito = BLAtencionMedica.registrarAtencion(
                    citaReal,
                    txtMotivoConsulta.getText(),
                    txtAntecedentes.getText(),
                    txtSignosVitales.getText(),
                    txtDiagnostico.getText(),
                    txtTratamiento.getText(),
                    TxtObservaciones.getText()
            );

            if (exito) {
                JOptionPane.showMessageDialog(this, "Atención médica registrada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                lblEstado.setText("Estado: ATENDIDA");
            }
        } catch (DatosInvalidosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Atención", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar atención: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void limpiarCampos() {
        txtIdCita.setText("");
        lblNombrePaciente.setText("Nombre del Paciente: -");
        lblEstado.setText("Estado: -");
        txtMotivoConsulta.setText("");
        txtSignosVitales.setText("");
        txtAntecedentes.setText("");
        txtDiagnostico.setText("");
        txtTratamiento.setText("");
        TxtObservaciones.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtObservaciones;
    private javax.swing.JButton btnBuscarCita;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lblAntecentes;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdCita;
    private javax.swing.JLabel lblMotivoConsulta;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JLabel lblSignoVitales;
    private javax.swing.JPanel panDiagnostico;
    private javax.swing.JPanel panInfoCita;
    private javax.swing.JTextField txtAntecedentes;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtIdCita;
    private javax.swing.JTextField txtMotivoConsulta;
    private javax.swing.JTextField txtSignosVitales;
    private javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
